### ISSUE TITLE
ansible-galaxy

### ISSUE THREAD

**Issue by Raffaello** [picotrading/ansible-rabbitmq#7]
it seems this role is not registered in ansible galaxy repository.

it add a great value to it to add to ansible galaxy

**Comment by jtyr** [comment]
This role is obsolete. Please use [this one](https://github.com/jtyr/ansible-rabbitmq) instead.

**Comment by Raffaello** [comment]
i will, but i cannot find it on ansible galaxy. Could you refer the link to ansible galaxy too?

**Comment by jtyr** [comment]
It was somehow named incorrectly (`rabitmq` instead of `rabbitmq`). I have fixed it and the Galaxy link is [here](https://galaxy.ansible.com/jtyr/rabbitmq/).

**Comment by Raffaello** [comment]
thanks
